import type {
  AiCapabilities,
  AiProvider,
  AiRawResult,
  AiTaskRequest,
  ConnectionResult,
} from "./provider.js";
import type { TokenChangeProposal } from "./proposal.js";

/**
 * Deterministic mock provider for development and tests. Canned proposals
 * per task; the default derives a tiny semantic proposal from the request
 * context so end-to-end flows exercise real paths.
 */

export interface MockProviderOptions {
  /** Override the response per task id (raw text — may be malformed on purpose). */
  readonly responses?: Readonly<Record<string, string>>;
  /** Simulate a connection failure. */
  readonly offline?: boolean;
}

export class MockProvider implements AiProvider {
  readonly id = "mock";
  readonly name = "Mock (deterministic)";

  constructor(private readonly options: MockProviderOptions = {}) {}

  capabilities(): AiCapabilities {
    return { structuredOutput: true, streaming: false, toolCalling: false, local: true };
  }

  testConnection(): Promise<ConnectionResult> {
    if (this.options.offline === true) {
      return Promise.resolve({
        ok: false,
        detail: "Looked up the mock endpoint → simulated offline",
      });
    }
    return Promise.resolve({ ok: true, detail: "Mock provider ready", model: "mock-1" });
  }

  generateProposal(request: AiTaskRequest): Promise<AiRawResult> {
    const override = this.options.responses?.[request.task];
    if (override !== undefined) {
      return Promise.resolve({ text: override, model: "mock-1" });
    }

    // Default: propose one semantic alias to the first color in context.
    const firstColor = request.context.tokens.find((token) => token.type === "color");
    const targetSet = firstColor?.set ?? request.context.sets[0] ?? "global";
    const proposal: TokenChangeProposal = {
      summary: `Mock proposal for ${request.task}`,
      assumptions: ["This is the deterministic mock provider."],
      operations: [
        {
          op: "create",
          set: targetSet,
          path: "semantic.mock.primary",
          type: "color",
          value: firstColor ? `{${firstColor.path}}` : "#3b82f6",
          description: "Generated by the mock provider",
        },
      ],
    };
    // Wrapped in a fence to exercise the real extraction path.
    return Promise.resolve({
      text: "Here is the proposal:\n```json\n" + JSON.stringify(proposal, null, 2) + "\n```",
      model: "mock-1",
    });
  }
}
